### ISSUE TITLE
Difficult to use conda install 

### ISSUE THREAD

**Issue by ld9866** [tprodanov/locityper#3]
Dear developer：
we want to try the locityper in our data but we found it is difficult to install.

conda install -c bioconda locityper
Channels:
 - bioconda
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides _openmp_mutex * *_llvm needed by locityper-0.13.4-h919a2d8_0

Could not solve for environment specs
The following packages are incompatible
└─ locityper is not installable because there are no viable options
   ├─ locityper [0.13.4|0.14.4|0.14.5|0.15.0|0.15.1] would require
   │  └─ _openmp_mutex * *_llvm, which does not exist (perhaps a missing channel);
   └─ locityper [0.15.2|0.15.3] would require
      └─ libgcc-ng >=12 , which does not exist (perhaps a missing channel).

We want to know how to solve the problem ?

**Comment by tprodanov** [comment]
Did you manage to install Locityper with conda?
If not, I can advise three possible ways to resolve the problem:
1. Add `conda-forge` channel:
```bash
conda config --add channels conda-forge
conda config --add channels bioconda
```
2. Use `mamba` instead of `conda`: `mamba install locityper`
3. Create new environment specifically for Locityper:
```bash
conda create --name locityper locityper
conda activate locityper
```
