### ISSUE TITLE
fasta instead of vcf

### ISSUE THREAD

**Issue by Hanjunmin** [tprodanov/locityper#6]
Hi,

This is a great tool!
I wanted to ask if it's possible to use a haplotype FASTA file instead of a VCF file？
Thanks a lot!

**Comment by tprodanov** [comment]
Hi Junmin!

Do you mean provide a FASTA with haplotypes for a given locus, or all haplotype assemblies across the whole genome? In the first case, you can provide it via `-l` argument (`-l locus chr:start-end haplotypes.fa`) or in a BED file (`-L`):
```
chrom   start   end   name   path/to/haplotypes.fa
```

Extracting haplotypes from the whole genome assemblies is not implemented, but I am sure it is possible with other tools, if you need to do that, I can try to post a script to do that.

Please ask if you have any more questions and thank you for using our tool!

**Comment by Hanjunmin** [comment]
Hi,
Thank you for the quick response！
What I mean is that I don't have the VCF file here: `locityper add -d db -v hprc.vcf.gz -r genome.fa -j counts.jf -L loci.bed`, but I do have the haplotype fasta files for all samples in a certain region. I just want to proceed to the next step of short reads genotyping, which seems to be what you referred to as the second option?

**Comment by tprodanov** [comment]
If you already have haplotypes in a certain region, this is the first option, just provide them via `-l locus_name chrom:start-end haplotypes.fa`.

**Comment by Hanjunmin** [comment]
Hi！
I met a error when run this tool, there are many warnings and it shows " Too many hash collisions"
[02:48:33  WARN] Read A00297:158:HT275DSXX:3:1528:9245:8985 produced hash collision (vPbmdEhyPHY)
[02:48:33 DEBUG]     Use 80614 reads. Discard 7500 unmapped, 38 out of bounds and 157264 with few unique k-mers
[02:48:33 ERROR] Error in locus NPHP1: Runtime error: Too many hash collisions (105474)
[02:48:33 ERROR] Failed at 1 loci
[02:48:33  INFO] Total time: 0:00:49.321

**Comment by Hanjunmin** [comment]
Hi！
I met a error when run this tool, there are many warnings and it shows " Too many hash collisions"
[02:48:33 WARN] Read A00297:158:HT275DSXX:3:1528:9245:8985 produced hash collision (vPbmdEhyPHY)
[02:48:33 DEBUG] Use 80614 reads. Discard 7500 unmapped, 38 out of bounds and 157264 with few unique k-mers
[02:48:33 ERROR] Error in locus test: Runtime error: Too many hash collisions (105474)
[02:48:33 ERROR] Failed at 1 loci
[02:48:33 INFO] Total time: 0:00:49.321

**Comment by Hanjunmin** [comment]
> Hi！ I met a error when run this tool, there are many warnings and it shows " Too many hash collisions" [02:48:33 WARN] Read A00297:158:HT275DSXX:3:1528:9245:8985 produced hash collision (vPbmdEhyPHY) [02:48:33 DEBUG] Use 80614 reads. Discard 7500 unmapped, 38 out of bounds and 157264 with few unique k-mers [02:48:33 ERROR] Error in locus test: Runtime error: Too many hash collisions (105474) [02:48:33 ERROR] Failed at 1 loci [02:48:33 INFO] Total time: 0:00:49.321

Is it because the regions I want to genotype have many similar segments (duplications)?

**Comment by tprodanov** [comment]
No, that should not be the case. If possible, could you please send me the output directory?

**Comment by Hanjunmin** [comment]
Sure!
I upload it :
https://drive.google.com/file/d/1o4S3_S-ru3WkHSgmC0kd5PHC0gAyGaJb/view?usp=sharing

**Comment by tprodanov** [comment]
It looks like you have paired end reads that were provided as single end reads. Is that possible? If that's the problem, I will update error message to be more understandable in the future versions.

**Comment by Hanjunmin** [comment]
OK, I have solved it, thank you !
